# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ 
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = 
    {
      consoleLogLevel = 0;
      extraModulePackages = [ ];
      kernelModules = [ "kvm-intel" ];
      kernelPackages = pkgs.linuxPackages_latest;
      kernelParams = 
        [ 
          "quiet" 
          "udev.log_level=3" 
        ];

      initrd = 
        {
          availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
          kernelModules = [ "dm-snapshot" ];

          luks = 
            {
              devices = 
                {
                  crypted = 
                    {
                      allowDiscards = true;
                      device = "/dev/disk/by-partuuid/c1991d90-f19c-4a8b-b80e-bfad09951f86"; 
                      header = "/dev/disk/by-partuuid/23941aec-3dd5-d74f-b1a9-fbb91f038cae";
                      preLVM = true;
                    };
                };
            };

          verbose = false;
        };

      loader = 
        {
          systemd-boot =
            {
              configurationLimit = 5;
              enable = true;
            };

          efi.canTouchEfiVariables = true;
        };
    };

  fileSystems = {
    "/" =
      { device = "/dev/disk/by-label/nixos";
        fsType = "ext4";
      };

  "/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
  };

  hardware = 
    {
      bluetooth.enable = true;
      cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };

  networking =
    {
      interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
      useDHCP = lib.mkDefault true;
    };

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  swapDevices =
    [ 
      { device = "/dev/disk/by-label/swap"; }
    ];

}

